[workspace]
authors = ["Jack Mirenzi <jmirenzi717@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly","conda-forge"]
name = "GD-tests"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026022505,<0.27"
python = ">=3.14.3,<3.15"
numpy = ">=2.4.2,<3"
matplotlib = ">=3.10.8,<4"
plotly = ">=6.5.2,<7"
jax = ">=0.7.2,<0.8"
