[workspace]
authors = ["Jack Mirenzi <jmirenzi717@gmail.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "gpu-intro"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.5.0,<26"
